### ISSUE TITLE
Label is floated on select-mutliple with jQuery > 3.0

### ISSUE THREAD

**Issue by apriljunge** [Baedda/floating-form-labels#16]
> As of jQuery 3.0, if no options are selected, it returns an empty array; prior to jQuery 3.0, it returns null.
http://api.jquery.com/val/#entry-longdesc

This causes that labels are always floated on select-mutliples. Even when nothing is selected

**Comment by Baedda** [comment]
@apriljunge could you please check if 1c81b62 fixes your problem?

**Comment by apriljunge** [comment]
Works for me 👍 Thanks

**Comment by Baedda** [comment]
Fixed in [v1.2.2](https://github.com/Baedda/floating-form-labels/releases/tag/v1.2.2)
