### ISSUE TITLE
Empty Placeholder-Attribute triggers floating of form-label

### ISSUE THREAD

**Issue by michael-jahn-dev** [Baedda/floating-form-labels#19]
If there is an empty HTML-Attribute `placeholder=""` then floating-form-labels triggers and the label gets placed above the field.

The fix is fairly easy: The `_hasPlaceholder` method should also check for empty placeholders like so:
```javascript
_hasPlaceholder: function () {
     if (typeof this.input.attr('placeholder') !== 'undefined' && this.input.attr('placeholder') !== '') {
            return true;
      }
      return false;
},
```

**Comment by apriljunge** [comment]
Maybe it would make sense to use [$.trim()](https://api.jquery.com/jquery.trim/).
For `$.trim(undefined)` and `$.trim(null)` jQuery returns an empty string. This could reduce the code to
```javascript
_hasPlaceholder: function () {
     if ($.trim(this.input.attr('placeholder')) !== '') {
            return true;
      }
      return false;
},
```

**Comment by Baedda** [comment]
I think using $.trim is definitely the cleaner implementation than asking for empty string, undefined, null, false, 0 and what else we could imagine for ourself.
