### ISSUE TITLE
Create animated gif preview of demo usage

### ISSUE THREAD

**Issue by jChris85** [Baedda/floating-form-labels#2]
We would like to have a animated gif of the demo (http://codepen.io/jChris85/pen/jrZypv). Implement the gif in the readme.md file underneath the first paragraph.

**Comment by ghost** [comment]
I'm taking this one. @jChris85 any preference where to put the gif in the repository?

**Comment by ghost** [comment]
Uploading the image here instead to avoid putting it in the repository or on a third-party image hosting

![Floating Form Labels Demo](https://cloud.githubusercontent.com/assets/412895/19562456/97680886-9706-11e6-8cd1-db01a113b51b.gif)

**Comment by jChris85** [comment]
Please could you slow down the gif a little bit to see the floating label animation better? Also could you integrate the gif after the first paraph in readme?

"...Take a look to the blog post from Brad Frost to understand why this is essential when dealing with inline form labels."

GIF HERE

**Comment by ghost** [comment]
Re-recorded the GIF, in better quality as well.

![ezgif-293978174](https://cloud.githubusercontent.com/assets/412895/19565872/9ff91416-9712-11e6-8f2f-2e05fe6ac5d2.gif)

Is that one ok?

**Comment by jChris85** [comment]
Looks very nice.

**Comment by ghost** [comment]
I'll push a new commit to the PR in the hour to come.
