### ISSUE TITLE
Does this support selects?

### ISSUE THREAD

**Issue by nathanaa5** [Baedda/floating-form-labels#22]
The readme says this supports floating labels on input and textarea - does it also support select (dropdown)?

**Comment by apriljunge** [comment]
This is not enabled by default. You can enable selects by adding an option:
```javascript
$('.ffl-wrapper').floatingFormLabels({
  formElements: 'input, textarea, select'
});
```

**Comment by Baedda** [comment]
We didn't enable monitoring selects by default because a select always has a value (the first option). To combine FFL with selects you would have to set the first option empty - what could be not wanted in every use case. @nathanaa5 does this answer your question?

**Comment by nathanaa5** [comment]
@Baedda even if there is always a value, it is still useful to display the floating label in a style consistent with inputs. Ideally there would be three cases covered:

1. No blank option, first item is default. In this case it doesn't show the placeholder, instead the floating label displays above the value.
1. Blank option. In this case the placeholder displays whenever the blank option is selected. Otherwise it shows the floating label.
1. No blank option, no default. In this case the placeholder displays until the user selects a value. Once they select one, it displays the floating label. The user can never go back to the unselected state.

Here you can see how the [material design select](https://material-components.github.io/material-components-web-catalog/#/component/select) shows a placeholder until the user selects a value. According to [the documentation](https://material.io/develop/web/components/input-controls/select-menus/), case 1 is the default, case 2 is handled by just adding a blank, and they handle case 3 as follows:

> By default, <select> elements will select their first enabled option. In order to initially display a placeholder instead, add an initial <option> element with the disabled and selected attributes set, and with value set to "".
> 
> <option value="" disabled selected></option>

**Comment by apriljunge** [comment]
@nathanaa5 Floating form labels does exactly behave like you described it.

1.  If there is no blank option, it is better not to add the select to the options and set the floatedClass (by default its `ffl-floated`) manually to the wrapper, to prevent the foating animation on the first load.
2. This is exactly the behaviour if you use it like i described above
3. What you describe is option 2, but you disable the first empty option with the `disabled` attribute. Technically it is the same

**Comment by Baedda** [comment]
Closed this because we "support" selects and there haven't been any new input by @nathanaa5
