### ISSUE TITLE
Can you plase upload a CSS version?

### ISSUE THREAD

**Issue by jaimestuardo** [Baedda/floating-form-labels#24]
Hello, I cannot use SASS in my ASP.NET MVC site. Can you upload a CSS version of the styles?

Thanks
Jaime

**Comment by michael-jahn-dev** [comment]
Hello Jaime,

I'd suggest using Sassmeister (https://www.sassmeister.com) or any other
online Sass playground where you could transpile it yourself and integrate
the css output manually.

Greetings
Miw0

Am Do., 22. Nov. 2018, 20:12 hat jaimestuardo <notifications@github.com>
geschrieben:

**Comment by Baedda** [comment]
Hi @jaimestuardo,
the reason why we do not have a transpiled css inside the package is that the reserved space depends on your project styling. We cannot guess how the value for "top" has to be in your case. This is why Sass is a dependency here.

**Comment by Baedda** [comment]
@jaimestuardo was this understable? Can I close this issue?

**Comment by jaimestuardo** [comment]
Yes.. you can close it..... finally, I have implemented my own floating labels, using only CSS... not JavaScript and it works perfectly.

thanks anyway.

Cheers
Jaime
