### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by ghost** [Baedda/floating-form-labels#4]
The demo is not working as it for me. I get the following error:

![desctop screenshot](https://cloud.githubusercontent.com/assets/412895/19563087/f16ad3ca-9708-11e6-835a-2116755caa9b.png)

To solve the issue, change the Javascript dependency URL from `https://raw.githubusercontent.com/...` to `https://rawgit.com/...`.
See [rgrove/rawgit](https://github.com/rgrove/rawgit) for details.

**Comment by jChris85** [comment]
Thanks a lot for the hint and the solution!!!
