### ISSUE TITLE
Check for spelling and grammar in readme.md

### ISSUE THREAD

**Issue by jChris85** [Baedda/floating-form-labels#5]
We would like to check for spelling and grammar in the readme.md by a native english speaking person. Please fix any mistakes or enhancements.

**Comment by flyingfisch** [comment]
Starting on this now :)

**Comment by David-Egan** [comment]
@jChris85 Already made a few tweaks before flyingfisch commented (my bad for not claiming the issue).  Would you still want to see my changes?

**Comment by jChris85** [comment]
@itsdegan sure. Just do a pull request and I will take a look.

**Comment by flyingfisch** [comment]
@itsdegan yeah, go ahead and submit a pull request so I can make sure my changes don't conflict. ;)

**Comment by flyingfisch** [comment]
Nevermind, just noticed you already did, taking a look now :)

**Comment by David-Egan** [comment]
Nice!  If either of you see any issues with what I did lemme know new to this sort of Github project and I'd like to help as much as possible.

**Comment by flyingfisch** [comment]
@itsdegan I'm about to incorporate some of your edits into my commit, if you could move your edits from README.txt to README.md and commit that first, it will probably help with the merge process. ;)

**Comment by flyingfisch** [comment]
(basically, copy/paste `README.txt`'s contents into `README.md`, delete `README.txt`, commit, and push.)

Also congrats on your first pull request, and welcome to the Github community! :)

**Comment by David-Egan** [comment]
Oops, from the look of your commit you no longer need me to move the content of README.txt into README.md?  And thank you :)

**Comment by flyingfisch** [comment]
@itsdegan go ahead and do it anyway, that way @jChris85 can merge up your PR first, and then merge up mine, and the edits to the file will stay intact. ;)

**Comment by David-Egan** [comment]
Done, thanks again for the help.  Is it bad to clog issues with comments like this (if so sorry :p)

**Comment by flyingfisch** [comment]
@itsdegan that works! :)

@jChris85 I think these are ready to merge. @itsdegan's PR should be merged first, then mine, since mine should overlay on his changes to a certain extent.

Thanks!

**Comment by jChris85** [comment]
@flyingfisch @itsdegan: Thank you. We will review your request on monday.

**Comment by flyingfisch** [comment]
Sounds good, thank you . Have a nice weekend!
